### ISSUE TITLE
"Show, attend and tell" block diagram in handout

### ISSUE THREAD

**Issue by jessejchuang** [2017-fall-DL-training-program/ImageCaption#12]
Hi TA,
I have two questions.

1. In CaptionModel.py, **the last line of TODO is _output__ = W1*_xt_ + W2*_C_ + output**. That's **_yt_ depends on _xt_, _ct_ and _the LSTM output_**. However, the **MLP in handout's block diagram seems lacking _xt_**. Furthermore, **LSTM output to MLP in the block diagram should use another notation** instead of using _**ht**_. Or I misunderstand your expression? 

2. The **_yt_ in handout's block diagram depends on _ct_ and _ht_**. However, **the equation (2) of Kelvin Xu's paper shows P(_yt_|a,yj<t-1) ~= exp{Lo(Eyt-1 + Lhht + Lzzt)}**. That's **_yt_ depends on _yt-1_, _ht_ and _ct_(i.e. _zt_ in the paper)**. It seems mismatched. Do I miss anything?

**Comment by connie980149** [comment]
For your questions,
1. Thanks for your reminder that the block diagram is missing the link of xt.

2. The **output of rnn is a linear transformation of the hidden** (ht), so the **Lhht** in the paper can be replaced by the output of rnn.

3. In my experience, since your training epoch is short, it's fine to use the output of rnn as the output of core if you want to see the effect of attention model.
