### ISSUE TITLE
Dim of the output of the attention model

### ISSUE THREAD

**Issue by Peter-Chuang** [2017-fall-DL-training-program/ImageCaption#7]
Dear TA,

Could you give a hint of the Dim of the output of the attention model?
For example, what are the Dims of "alpha, output, state" in ShowAttendTellCore?
The  Dims of "alpha, output, state" in TopDownCore?
The  Dims of "alpha, z" in Attention?

Peter

**Comment by connie980149** [comment]
alpha : the feature map (batch x 49 )
z : the context vector (C) (batch x 2048)

**Comment by Peter-Chuang** [comment]
Thank you!
How about the Dims of "alpha, output, state" in ShowAttendTellCore?
And the Dims of "alpha, output, state" in TopDownCore?
Thank you.

**Comment by connie980149** [comment]
In ShowAttendTellCore:
alpha : the feature map (batch x 49 )
output : output of LSTM (batch x rnn_size)
state: state of LSTM (1 x batch x rnn_size, 1 x batch x rnn_size)

In TopDownCore:
alpha : the feature map (batch x 49 )
output : output of LSTM (batch x rnn_size)
state: state of LSTM (2 x batch x rnn_size, 2 x batch x rnn_size)

Notice that the batch here is 5 times of batch size because the model take 5 caption-image pair for each image (done in train.py, keyword: opt.seq_per_img)

**Comment by Peter-Chuang** [comment]
Thank you!
